# Configuration file for the s3lst-ds project
# NOTE: to know more about the fields of the present file, check
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/.

# ---> Main project metadata
[project]
name = "s3lst-ds"
version = "0.1.10"
description = "A package for downscaling Sentinel-3 LST data using a scale-invariance-based model."
authors = [
    { name = "Élio Pereira", email = "elio.pereira@tuta.io" },
    { name = "Manvel Khudinyan", email = "khudinyan@colabatlantic.com" },
]

# Keywords (to improve discoverability and the dependencies that are required to install
# the package)
keywords = [
    "Sentinel-3",
    "Landsat 8-9",
    "Land Surface Temperature",
    "Downscaling",
    "Scale Invariance",
    "Data Science",
    "Machine Learning",
    "Remote Sensing",
]


readme = "README.md"
# Licenses' identifiers
# NOTE: Check
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license to know
# more about the license field.
# NOTE: Check https://spdx.org/licenses/ for a list of valid identifiers.
# NOTE: For the case of proprietary licenses `"LicenseRef-Proprietary"` should be used
# (https://packaging.python.org/en/latest/guides/licensing-examples-and-user-scenarios/#i-have-a-private-package-that-won-t-be-distributed).
# NOTE: MIT license: https://spdx.org/licenses/MIT.html
license = "MIT"
# Glob paths to the license files
# NOTE: Check
# https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-a-license
# to how to create a license file.
# NOTE: MIT license file: https://choosealicense.com/licenses/mit/
# WARNING: [year] and [fullname] entries in the file must be replaced.
# NOTE: "LICEN[CS]E*" is a glob pattern that matches both "LICENSE" (american english)
# and "LICENCE" (british and commonwealth english) files with additional suffixes.
license-files = ["LICEN[CS]E*"]

# PyPI classifiers
# NOTE: Check https://pypi.org/classifiers/ for a list of valid classifiers.
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Operating System :: Unix",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: GIS",
    "License :: OSI Approved :: MIT License",
]

# Minimum version of Python that is supported
requires-python = ">=3.13"

# Runtime dependencies (the main dependencies that are required to run the package)
dependencies = [
    "fastparquet>=2026.5.0",
    "geopandas>=1.1.4",
    "netcdf4>=1.7.4",
    "optuna>=4.9.0",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "rioxarray>=0.23.0",
    "scikit-learn>=1.9.0",
    "tqdm>=4.70.0",
]

# ---> Additional dependency groups for development
# NOTE: Command `uv sync --group GROUP` will install the dependencies in the group
# `GROUP` besides the runtime ones.
[dependency-groups]
dev = ["pre-commit>=4.6.1", "ruff>=0.16.1"]
docs = ["ipykernel>=7.3.0", "ipython>=9.16.0"]


# ---> Additional dependency groups for usage
# NOTE: After publishing to PyPI, command `pip install s3lst-ds[GROUP]` can install the
# dependencies in the group `GROUP` besides the runtime ones. For more details, read
# https://docs.astral.sh/uv/concepts/projects/dependencies/#multiple-sources. In the
# case of using the project repository, command `uv sync --extra GROUP` may be used to
# install the group dependency.
[project.optional-dependencies]
# Python wrapper for SNAP
snap = ["esa-snappy>=1.1.3"]

# ---> Scripts that can be run from the command line after installing the package
# NOTE: After installation, command `uv run COMMAND` where COMMAND is the key herein
# given to the respective module path and function (COMMAND = "MODULE_PATH:FUNCTION")
# will be available to run the function.
[project.scripts]
# Set CDSE credentials as environment variables
s3lst-ds-set-cdse = "s3lst_ds.cli:set_cdse"
# Remove CDSE credentials
s3lst-ds-unset-cdse = "s3lst_ds.cli:unset_cdse"
# (Re)install SNAP and configure snappy
s3lst-ds-install-snap = "s3lst_ds.cli:install_snap"
# Uninstall SNAP
s3lst-ds-uninstall-snap = "s3lst_ds.cli:uninstall_snap"
# Configure snappy
s3lst-ds-configure-snap = "s3lst_ds.cli:configure_snap"

# ---> URLs associated with the project
# NOTE: Check https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#urls
# to know more about the URLs field.
[project.urls]
Homepage = "https://github.com/CoLAB-ATLANTIC/s3lst-ds"
Repository = "https://github.com/CoLAB-ATLANTIC/s3lst-ds"
Issues = "https://github.com/CoLAB-ATLANTIC/s3lst-ds/issues"


# ---> Build backend tool
# NOTE: The build backend tool is responsible for creating the distribution package
# (check
# https://packaging.python.org/en/latest/tutorials/packaging-projects/#choosing-a-build-backend
# for more details).
# NOTE: Hatchling tool has many benefits compared to the ubiquitous setuptools (check
# https://hatch.pypa.io/1.8/why/)
[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
# Location of the source code of the package to be used by the Hatchling build backend
# NOTE: https://github.com/pypa/hatch/blob/master/docs/config/build.md#packages
packages = ["src/s3lst_ds"]


# ---> Development tools' configurations
# ruff configuration
# NOTE: https://github.com/astral-sh/ruff#configuration
[tool.ruff]
# Assume a python version
target-version = "py313"
# Line maximum length
line-length = 88
# Indentation width
indent-width = 4
